spring.application.name=livechat
spring.datasource.url=jdbc:mysql://localhost:3307/live_chat?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.tool.schema=DEBUG

## 1. Enable script generation
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#
## 2. Define where the file should be saved
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/schema.sql
#
## 3. (Optional) Format the SQL for readability
#spring.jpa.properties.hibernate.format_sql=true
#
## 4. Set the database dialect (helps Hibernate write the correct SQL syntax)
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect